let num = [5, 8, 2, 9, 3];
console.log(`Nosso array é ${num}`); // PARA ACRESCENTAR VALORES PARA AS NOSSAS ARRAYS, BASTA COLOCAR O CÓDIGO ABAIXO
num.push(7); // Ou num[3] = 7
// MAS NO CASO DO NUM[3] = 7, TEMOS QUE SABER O COMPRIMENTO DA NOSSA ARRAY. PARA ISSO, UTILIZAMOS O CONSOLE.LOG(NUM.LENGTH), OLHE O EXEMPLO ABAIXO.
// PODEMOS TAMBÉM UTILIZAR O NUM.SORT(). BASICAMENTE ELE VAI ORDENAR EM ORDEM CRESCENTE OS VALORES DA VARIÁVEL (ARRAY).
console.log(num.length);
console.log(`A nossa array agora é ${num}`);